-- ֵהװֱַ ּֿזב ַבדִבÝםה
CREATE TABLE Authors (
    Author_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ַבדÝÊַֽ ַבֳ׃ַ׃ם
    Name VARCHAR2(100) NOT NULL, -- ַ׃ד ַבדִבÝ
    Nationality VARCHAR2(50), -- ַבּה׃םֹ
    Birth_Year NUMBER(4) -- ׃הֹ ַבדםבַֿ
);

-- ֵהװֱַ ּֿזב ַבÊױהםÝַÊ
CREATE TABLE Categories (
    Category_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ַבדÝÊַֽ ַבֳ׃ַ׃ם
    Category_Name VARCHAR2(100) NOT NULL -- ַ׃ד ַבÊױהםÝ
);

-- ֵהװֱַ ּֿזב ַבßÊָ
CREATE TABLE Books (
    Book_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ַבדÝÊַֽ ַבֳ׃ַ׃ם
    Title VARCHAR2(200) NOT NULL, -- Úהזַה ַבßÊַָ
    Author_ID NUMBER NOT NULL, -- דÚׁÝ ַבדִבÝ
    Category_ID NUMBER NOT NULL, -- דÚׁÝ ַבÊױהםÝ
    ISBN VARCHAR2(20), -- ׁÞד ַבßÊַָ ַבֿזבם
    Publication_Year NUMBER(4), -- ׃הֹ ַבהװׁ
    Copies_Available NUMBER DEFAULT 0, -- Úֿֿ ַבה׃־ ַבדÊַֹֽ
    CONSTRAINT fk_books_authors FOREIGN KEY (Author_ID) REFERENCES Authors(Author_ID), -- ַבÚבַÞֹ דÚ ּֿזב ַבדִבÝםה
    CONSTRAINT fk_books_categories FOREIGN KEY (Category_ID) REFERENCES Categories(Category_ID) -- ַבÚבַÞֹ דÚ ּֿזב ַבÊױהםÝַÊ
);

-- ֵהװֱַ ּֿזב ַבֳÚײֱַ
CREATE TABLE Members (
    Member_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ַבדÝÊַֽ ַבֳ׃ַ׃ם
    Name VARCHAR2(100) NOT NULL, -- ַ׃ד ַבÚײז
    Email VARCHAR2(100) UNIQUE NOT NULL, -- ַבָׁםֿ ַבֵבßÊׁזהם
    Phone VARCHAR2(15), -- ׁÞד ַבוַÊÝ
    Address VARCHAR2(200), -- ַבÚהזַה
    Membership_Date DATE DEFAULT SYSDATE -- Êַׁם־ ַבÚײזםֹ
);

-- ֵהװֱַ ּֿזב ַבֵÚַַׁÊ
CREATE TABLE Borrowing (
    Borrowing_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ַבדÝÊַֽ ַבֳ׃ַ׃ם
    Book_ID NUMBER NOT NULL, -- דÚׁÝ ַבßÊַָ
    Member_ID NUMBER NOT NULL, -- דÚׁÝ ַבÚײז
    Borrow_Date DATE DEFAULT SYSDATE, -- Êַׁם־ ַבֵÚַֹׁ
    Return_Date DATE, -- Êַׁם־ ַבֵַּׁÚ
    Status VARCHAR2(20) DEFAULT 'Ûםׁ ד׃Êֿׁ', -- ַֽבֹ ַבֵÚַֹׁ
    CONSTRAINT fk_borrowing_books FOREIGN KEY (Book_ID) REFERENCES Books(Book_ID), -- ַבÚבַÞֹ דÚ ּֿזב ַבßÊָ
    CONSTRAINT fk_borrowing_members FOREIGN KEY (Member_ID) REFERENCES Members(Member_ID) -- ַבÚבַÞֹ דÚ ּֿזב ַבֳÚײֱַ
);
commit;